@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

abstract class ChanceCard{
-text : String

+getText()
+execute()
}

class DeckController{
-{static} chanceCardFile : String
-cardInfo : String[]
-FERRY : FieldType
-cards : ArrayList<ChanceCard>

+getCard()
+getOutOfJailCards()
}

class GetOutOfJailCard{
+execute()
}

class GoToJailCard{
+execute()
}

class MatadorCard{
+execute()
}

class MoveCard{
+execute()
-moveInReverseMode()
-moveInNormalMode()
}

class MoveToCard{
+execute()
}

class MoveToTypeCard{
+execute()
}

class PayPerHouseCard{
+execute()
}

class ReceivePerPlayerCard{
+execute()
}

class RecieveOrPayCard{
+execute()
}

abstract class Field{
-{static} name : String
-{static} position : int
-{static} type : FieldType
-{static} price : int
-{static} color : Color
-state : FieldState
}

class BuyableField{
-{static} housePrice : int
-{static} rent : int[]
}

enum Effect{
START
JAIL_GOTO
TAX_4000
TAX_2000
CHANCE
REFUGE
}

class EffectField{
-{static} effect : Effect
}

class FieldState{
-numOfHouses : int
-owner : Player
+pawned : boolean
}

enum FieldType{
START
STREET
CHANCE
TAX
FERRY
BREWERY
JAIL
REFUGE
}

class GameBoard{
-{static} gameBoard : GameBoard
-{static} fieldsInfo : String[]
-{static} fields : Field

-populateFieldsArray()
+getIndexOfJail()
+getNrOfFerriesOwnedByPlayer()
+getNrOfBreweriesOwnedByPlayer()
+getTotalHousesOwnedByPlayer()
+getTotalHotelsOwnedByPlayer()
+getTotalWealth()
+getActualWealth()
}

class Die{
- faceValue : int
-numberOfEqualRolls : int

+roll()
+getFaceValue()
+toString()
+EqualRolls()
}

class GameController{
-gui : GUI
-die : Die
-Players : Player[]
-currentDieRoll1 : int
-currentDieRoll2 : int
-sumOfDiceRolls : int
-deck : DeckController
-isReverseMode : boolean
-indexOfCurrentPlayer : int

+run()
-initialize()
+startGameLoop()
+getPlayers()
-getCurrentPlayer()
-addPlayersAndSetPosition()
-managePropertiesOrEndTurn()
-rollDice()
-resetEqualDieRolls()
-moveCurrentPlayer()
-movePlayer()
-movePlayerAndPassStart()
-hasReachedStartField()
-evaluateFieldAndExecute()
-executeEffect()
-payRentOrBuyProperty()
-checkJailStatus()
-locateOpponentFromName()
-sellAndBuyPropertiesFromOtherPlayers()
-areThereAnyHousesOnTheFields()
-sellAndBuyHousesAndPawn()
+canSellOneMoreHouse()
+canBuildOneMoreHouse()
+canPawnProperty()
+isAllowedBuildHouses()
+chosenStreetField()
+chosenBuyableField()
-areOwnedBySamePlayer()
+bankruptcyByPlayerOrBank()
+isBankrupt()
-doWeHaveAWinner()
-whoWon()
+masterTest()
}

class GUI{
- gui : gui_main.GUI
- gameController : GameController
- fields : GUI_Field[]
- gui_players : ArrayList<GUI_Player>

+populateFields()
+addCarsToBoard()
+addPlayersToBoard()
+displayDieRoll()
+moveCarToField()
+refreshPlayerBalance()
+displayRollDiceButton()
+displayPlayerSelectionButtons()
+displayJailOptions()
+displayUnownedPropertyOptions()
+displayLandingOnOpponentProperty()
+displayChanceCard()
+showDropDownMenu()
+chooseWhoYouWantToBuy()
+tryToSellProperty()
+soldOrKeptByPlayer()
+acceptOrDeclineOfferSelling()
+soldOrKeptByOpponent()
+tryToBuyProperty()
+acceptOrDeclineOfferBuying()
+buyOrSellProperties()
+buySellHouses()
+updateGUI()
+testButton()
+displayWinner()
}

class JailRules{
+PayOutOfJail()
+ForceOutOfJail()
+ForceJail()
}

class Main{

}

class Player{
- name : String
- jailed : boolean
- position : int

+setGetOutOfJailFreeCard()
+getGetOutOfJailFreeCard()
+isEliminated()
+setEliminated()
+getRoundsInJail()
+incrementRoundsInJail()
+resetRoundsInJail()
+getName()
+setName()
+getBalance()
+changeBalance()
+getPosition()
+setPosition()
+setJailed()
+isJailed()
}


class CsvReader{
+convertTo2DArray()
+NameToEffect()
}

class TxtReader{
+convertLinesToArray()
}

ChanceCard <|--  "3" MoveToTypeCard
ChanceCard <|-- "2" GetOutOfJailCard
ChanceCard <|-- "2" PayPerHouseCard
ChanceCard <|-- "2" GoToJailCard
ChanceCard <|-- "8" MoveToCard
ChanceCard <|-- "22" RecieveOrPayCard
ChanceCard <|-- "3" MoveCard
ChanceCard <|-- "3" ReceivePerPlayerCard
ChanceCard <|-- "1" MatadorCard

Field " 1 " <|-- " 1 " BuyableField
Field " 1 " <|-- " 1 " EffectField

GUI "1" -  "1" GameController
GameController " 1 " -- " 1 " DeckController
GameController " 1 " - " 1..2 "Die
GameController " 1 " -- " 3..6 "Player
GameController " 1 " -- JailRules
DeckController " 1 " - " 1..46 " ChanceCard

GameBoard " 1 " - " 40 " Field
Field " 1 " -- " 1 " FieldState
Field " 1 " -- " 1 " FieldType
Field " 1 " - " 1 "  Effect
Main - GameController

@enduml